


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 60000
  connection-timeout: 3000
  eureka:
    enabled: true
zuul:
  host:
    connect-timeout-millis: 5000
    max-per-route-connections: 10000
    max-total-connections: 5000
    socket-timeout-millis: 60000
  semaphore:
    max-semaphores: 500



spring:
  application:
    name: registration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
          defaultZone: https://gateway-server.azurewebsites.net/eureka/

